export const GET_PARTENAIRE="GET_PARTENAIRE"
export const PARENT_LOADING = 'PARENT_LOADING';
export const LOGIN_PARENT = 'LOGIN_PARENT';
export const REGISTER_PARENT = 'REGISTER_PARENT';
export const LOGOUT_PARENT= 'LOGOUT_PARENT';
export const GET_AUTH_PARENT = 'GET_AUTH_PARENT';
export const AUTH_ERRORS = 'AUTH_ERRORS';
export const PARTENAIRE_LOADING = 'PARTENAIRE_LOADING';
export const LOGIN_PARTENAIRE = 'LOGIN_PARTENAIRE';
export const REGISTER_PARTENAIRE = 'REGISTER_PARTENAIRE';
export const LOGOUT_PARTENAIRE= 'LOGOUT_PARTENAIRE';
export const GET_AUTH_PARTENAIRE = 'GET_AUTH_PARTENAIRE';
export const GET_USER = 'GET_USER';
export const GET_COMMENTS = 'GET_COMMENTS';
export const UPDATE_PARTENAIRE = 'UPDATE_PARTENAIRE'
 
